### ISSUE TITLE
Plugin crash on /reload

### ISSUE THREAD

**Issue by OzelotXD** [OopsieWoopsie/Spicord#1]
[17:53:37] [Server thread/INFO]: [Spicord] Enabling Spicord v1.0.3-SNAPSHOT*
[17:53:37] [Server thread/ERROR]: Error occurred while enabling Spicord v1.0.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at eu.mcdb.spicord.bukkit.SpicordBukkit.onEnable(SpicordBukkit.java:44) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:857) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.Bukkit.reload(Bukkit.java:607) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:55) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1790) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1598) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-498]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[17:53:37] [Server thread/INFO]: [Spicord] Disabling Spicord v1.0.3-SNAPSHOT
[17:53:37] [Server thread/INFO]: [Spicord] Disabling Spicord...
[17:53:37] [Server thread/ERROR]: Error occurred while disabling Spicord v1.0.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at eu.mcdb.spicord.Spicord.onDisable(Spicord.java:135) ~[?:?]
	at eu.mcdb.spicord.SpicordLoader.disable(SpicordLoader.java:101) ~[?:?]
	at eu.mcdb.spicord.bukkit.SpicordBukkit.onDisable(SpicordBukkit.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:857) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.Bukkit.reload(Bukkit.java:607) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:55) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1790) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1598) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-498]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by OopsieWoopsie** [comment]
Plugin **works** on Paper 1.13.2, you just did /reload and that happened.

**Comment by OopsieWoopsie** [comment]
Wow, I tried the plugin (version 1.0.1) on PaperSpigot 1.13.2 and this never happened... now the plugin does not even start...

**Comment by OopsieWoopsie** [comment]
Oh, I get it, I compiled a dev-build :| (which includes commands and it is not finished)

**Comment by OopsieWoopsie** [comment]
Fixed.
