### ISSUE TITLE
Logger error, after running own command

### ISSUE THREAD

**Issue by TrueMB** [OopsieWoopsie/Spicord#42]
Hello!

I am running a Discord Bot, which allows me to create todo Notes. After running this command the first time after v4.0.0, I got following error:

`[11:59:47 ERROR] [Spicord]: [JDA:RestAction] Encountered error while processing failure consumer
[11:59:47 ERROR]: java.lang.NullPointerException: Cannot invoke "java.util.logging.Level.intValue()" because the return value of "java.util.logging.Logger.getLevel()" is null
[11:59:47 ERROR]:       at org.spicord.log.LoggerImpl.isDebugEnabled(LoggerImpl.java:149)
[11:59:47 ERROR]:       at net.dv8tion.jda.internal.requests.RestActionImpl.lambda$static$1(RestActionImpl.java:51)
[11:59:47 ERROR]:       at net.dv8tion.jda.api.exceptions.ContextException$ContextConsumer.accept(ContextException.java:72)
[11:59:47 ERROR]:       at net.dv8tion.jda.api.exceptions.ContextException$ContextConsumer.accept(ContextException.java:57)
[11:59:47 ERROR]:       at net.dv8tion.jda.api.requests.Request.lambda$onFailure$1(Request.java:132)
[11:59:47 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
[11:59:47 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[11:59:47 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[11:59:47 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[11:59:47 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[11:59:47 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

I am pretty sure this should be not an issue from my side.

**Comment by OopsieWoopsie** [comment]
Hello, this indeed seems an issue in your side, and is probably related to the server software you are using. This should work fine on spigot

**Comment by OopsieWoopsie** [comment]
What server software are you using?

**Comment by TrueMB** [comment]
I am using the newest PaperMC Waterfall Version. But I needed to change the log Output. I guess it has something to do with that.

Here is my log4j2.xml
https://pastebin.com/Tgmae8xT

**Comment by OopsieWoopsie** [comment]
I will update Spicord's code to explicity set Logger.setLevel() and that should fix this problem

**Comment by OopsieWoopsie** [comment]
Hey, can you check if this build fixes the issue?

(Jar file is into the Zip file, as GitHub doesn't allows to upload files with the .jar extension)
[Spicord_4.0.0.zip](https://github.com/Spicord/Spicord/files/6703950/Spicord_4.0.0.zip)

**Comment by TrueMB** [comment]
Looking better so far. Still got an error. But need some time to look into that.

`[Spicord]: [JDA:RestAction] RestAction queue returned failure: [ErrorResponseException] 10014: Unknown Emoji`

**Comment by TrueMB** [comment]
Fixed my last issue. Works now perfectly. Thanks!
