### ISSUE TITLE
Players command BUG

### ISSUE THREAD

**Issue by LukyTechnology** [OopsieWoopsie/Spicord#57]
Hello! Spicord working nicely on 1.18.1 but ONLY one command dont working (players). When i use .players on discord spicord dont respond but when i use .info spicord send me answer. This is error when i use command .players

[18:51:56 ERROR] [Spicord]: [JDA:JDA] One of the EventListeners had an uncaught exception
[18:51:56 ERROR]: java.lang.NoClassDefFoundError: org/bukkit/command/CommandSender
[18:51:56 ERROR]:       at java.base/java.lang.Class.forName0(Native Method)
[18:51:56 ERROR]:       at java.base/java.lang.Class.forName(Class.java:375)
[18:51:56 ERROR]:       at org.spicord.util.VanishAPI.isPresent(VanishAPI.java:35)
[18:51:56 ERROR]:       at org.spicord.util.VanishAPI.get(VanishAPI.java:14)
[18:51:56 ERROR]:       at org.spicord.server.impl.BungeeServer.getServersAndPlayers(BungeeServer.java:66)
[18:51:56 ERROR]:       at org.spicord.addon.PlayersAddon.onCommand(PlayersAddon.java:51)
[18:51:56 ERROR]:       at org.spicord.bot.DiscordBot$BotCommandListener.onMessageReceived(DiscordBot.java:433)
[18:51:56 ERROR]:       at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:435)
[18:51:56 ERROR]:       at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821)
[18:51:56 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994)
[18:51:56 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[18:51:56 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[18:51:56 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[18:51:56 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[18:51:56 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[18:51:56 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[18:51:56 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[18:51:56 ERROR]: Caused by: java.lang.ClassNotFoundException: org.bukkit.command.CommandSender
[18:51:56 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[18:51:56 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[18:51:56 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[18:51:56 ERROR]:       ... 25 more

**Comment by anvorgesa** [comment]
Thanks for reporting the issue, it should be fixed in 4.2.1 :smile:
https://github.com/Spicord/Spicord/releases/tag/4.2.1
