### ISSUE TITLE
WebSocketException - Flushing frames to the server failed: Connection or outbound has closed

### ISSUE THREAD

**Issue by Firav** [OopsieWoopsie/Spicord#69]
Receiving error periodically within console.
```
[16:13:42 WARN]: net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection or outbound has closed
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:434)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.sendFrames(WritingThread.java:384)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:108)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:55)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[16:13:42 WARN]: Caused by: java.net.SocketException: Connection or outbound has closed
[16:13:42 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1291)
[16:13:42 WARN]:        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
[16:13:42 WARN]:        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
[16:13:42 WARN]:        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.flush(WritingThread.java:271)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:422)
[16:13:42 WARN]:        ... 4 more
[16:13:42 WARN]: net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection or outbound has closed
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:434)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.sendFrames(WritingThread.java:384)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:120)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:55)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[16:13:42 WARN]: Caused by: java.net.SocketException: Connection or outbound has closed
[16:13:42 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1291)
[16:13:42 WARN]:        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
[16:13:42 WARN]:        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
[16:13:42 WARN]:        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.flush(WritingThread.java:271)
[16:13:42 WARN]:        at Spicord_4.2.2.jar//net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:422)
[16:13:42 WARN]:        ... 4 more
```

Versions:
Paper - git-Paper-131 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 2da891f)
Spicord - 4.2.2

**Comment by anvorgesa** [comment]
https://github.com/Spicord/Spicord/issues/60#issuecomment-1075745723
