### ISSUE TITLE
Spicord fail to download library (Also no config file)

### ISSUE THREAD

**Issue by AriaVibes05** [OopsieWoopsie/Spicord#76]
[12:04:28 INFO] [Spicord]: [Loader] Downloading library com.moandjiezana.toml:toml4j:0.4.0
[12:06:38 ERROR] [Spicord]: Spicord could not be loaded, please report this error in 
	 -> https://github.com/Spicord/Spicord/issues
[12:06:38 ERROR]: java.net.ConnectException: Connection timed out
[12:06:38 ERROR]: 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[12:06:38 ERROR]: 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
[12:06:38 ERROR]: 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
[12:06:38 ERROR]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[12:06:38 ERROR]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[12:06:38 ERROR]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[12:06:38 ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[12:06:38 ERROR]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[12:06:38 ERROR]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[12:06:38 ERROR]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[12:06:38 ERROR]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[12:06:38 ERROR]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[12:06:38 ERROR]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[12:06:38 ERROR]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[12:06:38 ERROR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[12:06:38 ERROR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[12:06:38 ERROR]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[12:06:38 ERROR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
[12:06:38 ERROR]: 	at org.spicord.Library.connect(Library.java:50)
[12:06:38 ERROR]: 	at org.spicord.Library.download(Library.java:30)
[12:06:38 ERROR]: 	at org.spicord.LibraryLoader.downloadLibrary(LibraryLoader.java:79)
[12:06:38 ERROR]: 	at org.spicord.LibraryLoader.downloadLibraries(LibraryLoader.java:69)
[12:06:38 ERROR]: 	at org.spicord.SpicordLoader.<init>(SpicordLoader.java:65)
[12:06:38 ERROR]: 	at org.spicord.SpicordLoader.<init>(SpicordLoader.java:48)
[12:06:38 ERROR]: 	at org.spicord.bungee.SpicordBungee.onLoad(SpicordBungee.java:50)
[12:06:38 ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:399)
[12:06:38 ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:301)
[12:06:38 ERROR]: 	at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:143)
[12:06:38 ERROR]: 	at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63)
[12:06:38 ERROR]: 	at de.themoep.snap.Lmbda$19.execute(Unknown Source)
[12:06:38 ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[12:06:38 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[12:06:38 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[12:06:38 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:06:38 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:06:38 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:06:38 INFO] [Snap]: Loaded plugin Spicord version 5.0.2 by Sheidy
[12:06:38 INFO] [Snap]: Loaded plugin AzLink version 1.3.1 by Azuriom Team
[12:06:38 INFO] [Snap]: Loaded plugin CMIB version 1.0.2.2 by Zrips

java.lang.NullPointerException: Cannot invoke "org.spicord.config.SpicordConfiguration.getLoadDelay()" because the return value of "org.spicord.SpicordLoader.getConfig()" is null[12:06:38 WARN] [Snap]: Exception encountered when loading plugin: Spicord
	at org.spicord.bungee.SpicordBungee.onEnable(SpicordBungee.java:55) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[?:?]
	at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:144) ~[?:?]
	at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
	at de.themoep.snap.Lmbda$19.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by anvorgesa** [comment]
Hello, sorry for the late response, it looks like the error you are getting could be caused by a firewall that is blocking connections to web servers, here you can see the URLs of the required libraries https://github.com/Spicord/Spicord/blob/v5/common/src/main/resources/libraries.json

In order to solve the problem manually you have to download all of them and place them in the `plugins/Spicord/libs` folder, if the `libs` folder was not created then you will have to create it yourself, after that start the server and the plugin should create the configuration file and load as it should.

**Comment by AriaVibes05** [comment]
Okay thank you
