### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to spicord on Velocity 3.2.0

### ISSUE THREAD

**Issue by adaliszk** [OopsieWoopsie/Spicord#77]
First off, nice work with the plugin! I like the idea that we can write addons with simple JS!

However, on Velocity 3.2.0, once I enable any JS addons, I get the following error:
```
Couldn't pass ProxyInitializeEvent to spicord
Java.lang.NoClassDefFoundError: org/bukkit/plugin/EventExecutor
   at org.spicord.script.ModuleManager.registerDefaultModules(ModuleManager.java:104) ~[?:?]
   at org.spicord.script.RhinoModuleManager.<init>(RhinoModuleManager.java:33) ~[?:?]
   at org.spicord.script.RhinoScriptEngine.<init>(RhinoScriptEngine.java:64) ~[?:?]
   at org.spicord.script.ScriptEngine.lambda$static$0(ScriptEngine.java:31) ~[?:?]
   at org.spicord.script.ScriptEngine.lambda$getEngine$1(ScriptEngine.java:48) ~[?:?]
   at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
   at org.spicord.script.ScriptEngine.getEngine(ScriptEngine.java:48) ~[?:?]
   at org.spicord.addon.AddonManager.loadDirAddon(AddonManager.java:289) ~[?:?]
   at org.spicord.addon.AddonManager.loadAddons(AddonManager.java:194) ~[?:?]
   at org.spicord.Spicord.onLoad(Spicord.java:113) ~[?:?]
   at org.spicord.SpicordLoader.load(SpicordLoader.java:96) ~[?:?]
   at org.spicord.velocity.SpicordVelocity.onProxyInitialize(SpicordVelocity.java:63) ~[?:?]
   at org.spicord.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
   at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
   at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
   at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
   at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.EventExecutor
   at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
   at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
   ... 19 more
```

I tried with the MOTD addon and a custom one where I copied the basic example from the Wiki:

```json5
// spicord/addons/test_addon/addon.json
{
  "id": "test_addon",
  "name": "TestAddon",
  "author": "AdaLiszk",
  "version": "0.1",
  "main": "src/index.js"
}
```

```yaml
// spicord/addons/test_addon/data/config.yml
test: "HALLO"
```

```javascript
// spicord/addons/test_addon/src/index.js
const BaseAddon = require('base-addon')
const testAddon = new BaseAddon()

module.exports = testAddon
```

My config:
```ini
config_version = 1
loadDelay = 10
integrated_addon_footer = "Powered by Spicord v{version}"

[jda_messages]
enabled = true
debug = true

[[bots]]
name = "default"
enabled = true
token = "...valid-token-here..."
command_support = true
command_prefix = "!"
addons = [
  "spicord::info",
  "spicord::players"
]
```

Did the intended way of writing a JS plugin change in some way, or do I need to implement some methods before seeing my addon registered?

Some environmental information:
```yaml
System: Alpine 3.18
Java: openjdk17=17.0.8_p7-r0
Plugins:
- spicord v5.1.0
```
Additionally, I have tried with `openjdk16=16.0.2_p7-r4` as well, but getting the same result.

**Comment by anvorgesa** [comment]
Hello! Thank you for reporting this issue, it looks like I have forgot to only enable the "events" package for bukkit only and I mistakenly made it available on all platforms, thus causing a "class not found" error on a server other than bukkit, I will fix this asap.

**Comment by anvorgesa** [comment]
The latest version should not cause that issue, thank you very much for reporting it :+1: 
https://github.com/Spicord/Spicord/releases/tag/5.1.1
