### ISSUE TITLE
A strange error when disabling the plugin, as soon as I did not try to fix it

### ISSUE THREAD

**Issue by andrusharusakov** [OopsieWoopsie/Spicord#84]
ERROR:
```[03:56:24 ERROR]: [net.dv8tion.jda.api.JDA] Encountered exception trying to schedule event
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:550) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:250) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:191) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:160) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at Spicord_5.5.0 (1).jar/org.spicord.bukkit.server.BukkitServerScheduler.runTaskAsync(BukkitServerScheduler.java:26) ~[Spicord_5.5.0 (1).jar
:?]
        at Spicord_5.5.0 (1).jar/org.spicord.AbstractServerScheduler.execute(AbstractServerScheduler.java:21) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:68) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:175) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.JDAImpl.setStatus(JDAImpl.java:384) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.requests.WebSocketClient.handleDisconnect(WebSocketClient.java:471) ~[Spicord_5.5.0 (1).ja
r:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:465) ~[Spicord_5.5.0 (1).jar:
?]
        at Spicord_5.5.0 (1).jar/com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3691) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[Spicord_5.5.0 (1).jar:?]
        
        
        [03:56:24 ERROR]: [net.dv8tion.jda.api.JDA] Encountered exception trying to schedule event
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:550) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:250) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:191) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:160) ~[purpur-1.21.jar:1.21-2250-797ce6b]
        at Spicord_5.5.0 (1).jar/org.spicord.bukkit.server.BukkitServerScheduler.runTaskAsync(BukkitServerScheduler.java:26) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/org.spicord.AbstractServerScheduler.execute(AbstractServerScheduler.java:21) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:68) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:175) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.JDAImpl.setStatus(JDAImpl.java:384) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.JDAImpl.shutdown(JDAImpl.java:888) ~[Spicord_5.5.0 (1).jar:?]
        at Spicord_5.5.0 (1).jar/net.dv8tion.jda.internal.JDAImpl.shutdownNow(JDAImpl.java:877) ~[Spicord_5.5.0 (1).jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by ComboGame** [comment]
fix pls

**Comment by anvorgesa** [comment]
Hello! Release 5.6.0 is now available on SpigotMC, can you test it and tell me if the issue is fixed? Thanks!
